default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: susurrus_development
  username: postgres
  password: postgres
  host: localhost
  port: 5432

test:
  <<: *default
  database: susurrus_test
  username: postgres
  password: postgres

production:
  <<: *default
  database: susurrus_production
  username: postgres
  password: <%= ENV['TEST_PG_DATABASE_PASSWORD'] %>
