default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  adapter: postgresql
  database: susurrus_development
  pool: 5
  timeout: 5000
  username: postgres
  password: postgres

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  <<: *default
  database: susurrus_production
  username: postgres
  password: <%= ENV['TEST_PG_DATABASE_PASSWORD'] %>
